// The catalog mirrors the living fauna in the world, including ambient motes.
export const ATELIER_SPECIES = [
 { id:'lumen', name:'Lumens', number:'01', title:'A little moving light.', intro:'A soft pulse in the dark.\nA whole school moving as one.', character:'Elastic, luminous, easily startled.', home:'Sheltered fresh water', habitat:'Schools gather around lakes and river margins. Their light reads most clearly at night.', traits:[['A body made of light','A rounded volume breathes at rest, then stretches and bends with speed.'],['Safety in numbers','Schools drift together and scatter when approached.'],['Individual color','Hue, size, voice and movement differ between individuals.']], actions:[['rest','Rest'],['swim','Swim'],['flee','Flee']], voices:[['call','A quiet call'],['escape','A startled flutter']] },
 { id:'hopper', name:'Pebble hoppers', number:'02', title:'The stones are watching.', intro:'A patient little colony.\nThen, suddenly, legs.', character:'Watchful, sociable, quick to scatter.', home:'Stone patches and sheltered galleries', habitat:'Rocky ground, mountain lakeshores, cave mouths and dry cave interiors. Colonies need room to scatter and return.', traits:[['Almost a stone','The body settles low among ordinary rocks; small eyes keep watch.'],['A sudden change','Attention becomes a rise, a run, a brake and a careful settling.'],['A place to return to','After scattering, individuals regroup around their colony.']], actions:[['rest','Give space'],['approach','Approach'],['run','Startle']], voices:[['startle','A startled call'],['step','A foot on stone'],['settle','Settling down'],['creak','A quiet creak']] },
 { id:'reed', name:'Reed walkers', number:'03' },
 { id:'roundtail', name:'Roundtails', number:'04', bird:0, title:'A small, busy presence.', intro:'A peck. A hop. A glance.\nThe clearing is never quite still.', character:'Compact, curious, lightly restless.', home:'Clearings with a nearby perch', habitat:'Dry, gently sloping ground beside reachable branches. An open route lets it climb from the clearing to the tree.', traits:[['A round silhouette','The smallest bird profile, with a compact tail.'],['Quick rhythms','Shorter pauses, brisk hops and faster wingbeats distinguish it from its neighbors.'],['Color within a species','Several plumage palettes share the same anatomy.']] },
 { id:'longtail', name:'Longtails', number:'05', bird:1, title:'A line through the air.', intro:'A long tail follows the turn.\nA quiet balance on the branch.', character:'Slender, balanced, measured.', home:'Clearings with a nearby perch', habitat:'Open ground and reachable tree branches. It forages below, then takes an unobstructed flight to a perch.', traits:[['The tail carries the gesture','The long silhouette makes turns, glides and landings easy to read.'],['A measured pace','Its pauses and wingbeats fall between Roundtail and Crowncrest.'],['Shared habits, different dress','Plumage varies while the species keeps its characteristic proportions.']] },
 { id:'crowncrest', name:'Crowncrests', number:'06', bird:2, title:'No need to hurry.', intro:'A crest above the grass.\nA longer pause before flight.', character:'Larger, deliberate, quietly alert.', home:'Clearings with a nearby perch', habitat:'Gentle dry terrain with a nearby tree. Clear ground and a safe branch give it two places to rest.', traits:[['A recognizable crown','A crest and a larger body distinguish its silhouette.'],['Time to look around','Longer rests and slower wingbeats give it a more deliberate rhythm.'],['Individual plumage','Color varies within the same crowned form.']] },
 { id:'firefly', name:'Fireflies', number:'07', title:'Small lights, no destination.', intro:'A few drifting points.\nA landscape quietly breathing.', character:'Weightless, flickering, scattered.', home:'The night air', habitat:'Ambient motes drift above terrain and water; clusters also gather around landmarks. Their light responds to the night and the world’s sound.', traits:[['A pulse, not a steady lamp','Each mote has its own phase and brightness cycle.'],['A little color in the dark','Warm gold, cool cyan and pink lights mingle.'],['Small differences','Size, drift speed and phase keep the group from moving in lockstep.']], actions:[['rest','Drift'],['pulse','Sound response']], voices:[] }
];
export function atelierURL(id, seed = '') {
 const path = id === 'reed' ? './reed-study.html' : './fauna-atelier.html';
 const params = new URLSearchParams(); if (id !== 'reed') params.set('species', ATELIER_SPECIES.some(s=>s.id===id) ? id : 'lumen');
 if (seed) params.set('seed',seed); return path + (params.size ? '?' + params : '');
}
export function mountAtelierNavigation(id) {
 const seed = new URLSearchParams(location.search).get('seed') || '';
 const select = document.getElementById('atelier-species');
 for (const species of ATELIER_SPECIES) { const option=document.createElement('option'); option.value=species.id;option.textContent=species.number+' / '+species.name;select.append(option); }
 select.value=id; select.addEventListener('change',()=>location.assign(atelierURL(select.value,seed)));
 const params=new URLSearchParams();if(seed)params.set('seed',seed);
 document.getElementById('world-link').href='./'+(params.size?'?'+params:'');
 return seed;
}
