const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs');
(async()=>{const b=await chromium.launch({headless:true,args:['--use-angle=metal']});const results=[];try{
for(const [label,port,fps] of [['baseline',Number(process.env.BASELINE_PORT || 8798),0],['optimized',Number(process.env.OPTIMIZED_PORT || 8797),0],['balanced',Number(process.env.OPTIMIZED_PORT || 8797),60],['quiet',Number(process.env.OPTIMIZED_PORT || 8797),30]]){
const p=await b.newPage({viewport:{width:1440,height:900},deviceScaleFactor:2});const errors=[],warnings=[];p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text().slice(0,400));else if(m.type()==='warning')warnings.push(m.text().slice(0,400))});
await p.addInitScript(()=>{const raf=window.requestAnimationFrame;window.requestAnimationFrame=fn=>raf(t=>{const start=performance.now();try{fn(t)}finally{if(window.metrics)metrics.cpu.push(performance.now()-start)}})});
await p.route('**/js/main.js*',async route=>{const r=await route.fetch();let body=await r.text();body=body.replace('window.__debug = {','window.__debug = { pmrem, caves, watersideLife,');await route.fulfill({response:r,body})});
await p.goto(`http://127.0.0.1:${port}/25_Nowherelands_II/?seed=umbra&fps=${fps}`);await p.waitForFunction(()=>window.__debug,{timeout:120000});await p.waitForTimeout(12000);
await p.evaluate(()=>{const d=__debug;window.metrics={costs:{},frames:[],draws:[],triangles:[],cpu:[],last:performance.now()};d.renderer.info.autoReset=false;
const wrap=(o,k,l)=>{if(!o?.[k])return;const old=o[k];o[k]=function(...args){const t=performance.now();try{return old.apply(this,args)}finally{(metrics.costs[l]||=[]).push(performance.now()-t)}}};
for(const [o,k,l] of [[d.terrain,'update','terrain'],[d.terrain,'build','terrainBuild'],[d.terrain,'install','terrainInstall'],[d.terrain.vegetation,'addChunk','vegetationBuild'],[d.terrain.vegetation,'update','vegetationUpdate'],[d.shoreMap,'update','shore'],[d.fauna.model,'step','faunaStep'],[d.fauna.meshes,'update','faunaMeshes'],[d.birds,'update','birds'],[d.post,'render','render'],[d.pmrem,'fromScene','environment'],[d.environment,'update','environmentUpdate'],[d.pmrem,'fromCubemap','environmentFilter']])wrap(o,k,l);
const player=d.player.update;d.player.update=function(...args){metrics.begin=performance.now();d.renderer.info.reset();return player.apply(this,args)};
const post=d.post.render;d.post.render=function(...args){const v=post.apply(this,args),now=performance.now();metrics.frames.push(now-metrics.last);metrics.last=now;metrics.draws.push(d.renderer.info.render.calls);metrics.triangles.push(d.renderer.info.render.triangles);return v};
metrics.clear=()=>{metrics.costs={};for(const k of ['frames','draws','triangles','cpu'])metrics[k]=[];metrics.last=performance.now()};
});
const collect=async()=>p.evaluate(()=>{const summary=a=>{const s=a.slice().sort((a,b)=>a-b);return {n:s.length,mean:s.reduce((n,x)=>n+x,0)/s.length,p50:s[Math.floor(s.length*.5)],p95:s[Math.floor(s.length*.95)],max:s.at(-1)}};const d=__debug;return {...Object.fromEntries(['frames','cpu','draws','triangles'].map(k=>[k,summary(metrics[k])])),costs:Object.fromEntries(Object.entries(metrics.costs).map(([k,a])=>[k,summary(a)])),state:{population:d.fauna.model.creatures.length,veg:d.terrain.vegetation.chunks.size,terrain:d.terrain.stats,reflection:d.water.reflectionStats,environment:d.environment?.stats,worker:d.shared.surfaceWork&&{ready:d.shared.surfaceWork.ready,failed:d.shared.surfaceWork.failed,jobs:d.shared.surfaceWork.jobs.size,stats:d.shared.surfaceWork.stats},lods:d.fauna.meshes.lumenLods?.map(m=>m.count)}}});
await p.waitForTimeout(12000);const stationary=await collect();
await p.evaluate(()=>{const d=__debug;metrics.clear();metrics.motion=performance.now();metrics.origin=d.player.position.clone();metrics.yaw=d.player.yaw;const old=d.player.update;d.player.update=function(...args){const elapsed=(performance.now()-metrics.motion)/1000,x=metrics.origin.x-Math.sin(metrics.yaw)*elapsed*60,z=metrics.origin.z-Math.cos(metrics.yaw)*elapsed*60;this.position.set(x,Math.max(d.heightmap.height(x,z),d.heightmap.waterAt(x,z))+18,z);this.velocity.set(0,0,0);this.fly=true;return old.apply(this,args)}});
await p.waitForTimeout(20000);const movement=await collect();results.push({label,stationary,movement,errors,warnings});fs.writeFileSync(process.env.PERFORMANCE_OUTPUT || '/tmp/nowherelands-performance-comparison.json',JSON.stringify(results,null,2));console.log(label,JSON.stringify({stationary,movement,errors}));await p.close();
}
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
