const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,args:['--use-angle=metal','--mute-audio']});const report={offline:[],errors:[]};try{
const p=await browser.newPage();p.on('pageerror',e=>report.errors.push(String(e)));await p.route('**/__music_baseline__/**',route=>{const path=new URL(route.request().url()).pathname.split('/__music_baseline__/')[1];return route.fulfill({body:fs.readFileSync(process.env.BASELINE_DIRECTORY+'/'+path),contentType:'text/javascript'})});await p.goto('http://127.0.0.1:8797/25_Nowherelands_II/tests/browser/');
for(const options of [{fps:0,baseline:!!process.env.BASELINE_DIRECTORY},{fps:0},{fps:60},{fps:30},{fps:30,legacyGate:true}]){const r=await p.evaluate(async o=>{if(o.baseline){o.AudioEngineClass=(await import('/__music_baseline__/25_Nowherelands_II/js/audio/AudioEngine.js?v=pebble-audio-10')).AudioEngine;o.ConductorClass=(await import('/__music_baseline__/25_Nowherelands_II/js/audio/Conductor.js?v=pebble-audio-10')).Conductor;}return (await import('/25_Nowherelands_II/tests/MusicTimingChecks.js')).renderMusicTiming(o)},options);report.offline.push(r);console.log(r)}
const [base,...modes]=report.offline;report.comparisons=[];for(const r of modes){const diff=await p.evaluate(async ids=>(await import('/25_Nowherelands_II/tests/MusicTimingChecks.js')).compareMusicSamples(...ids),[base.id,r.id]);report.comparisons.push({fps:r.fps,legacyGate:r.legacyGate,...diff});console.log('PCM',r.fps,r.legacyGate,diff);if(!r.legacyGate&&(r.controlsHash!==base.controlsHash||diff.peakError>1e-5||diff.rmsError>1e-6))throw Error('Music changed with render frame limit');}if(modes.at(-1).controlsHash===base.controlsHash)throw Error('Replay did not detect the old timing regression');
await p.close();
const game=await browser.newPage({viewport:{width:900,height:600}});game.on('pageerror',e=>report.errors.push(String(e)));
await game.addInitScript(()=>{const raf=requestAnimationFrame;window.requestAnimationFrame=fn=>raf(t=>{const m=window.musicCadence;if(m)m.callbacks++;fn(t)})});
await game.goto('http://127.0.0.1:8797/25_Nowherelands_II/?seed=umbra');await game.waitForFunction(()=>window.__debug,{timeout:120000});await game.click('#enter');await game.waitForFunction(()=>__debug.shared.conductor);await game.waitForTimeout(2500);
await game.evaluate(()=>{const d=__debug;for(const[o,k,label]of[[d.shared.conductor,'update','music'],[d.shared.audio,'update','engine'],[d.player,'update','world'],[d.post,'render','render']]){const old=o[k];o[k]=function(...a){if(window.musicCadence)window.musicCadence[label]++;return old.apply(this,a)}}});
report.cadence=[];
for(const fps of [0,60,30]){await game.evaluate(fps=>{__debug.hud.frameRate=fps;window.musicCadence={callbacks:0,music:0,engine:0,world:0,render:0}},fps);await game.waitForTimeout(2000);const r=await game.evaluate(()=>{const r=window.musicCadence;window.musicCadence=null;return r});report.cadence.push({fps,...r});console.log('live',fps,r);if(r.music!==r.callbacks||r.engine!==r.callbacks||r.world!==r.callbacks)throw Error('Render pacing throttled music/world updates');if(fps&&r.render>fps*2+3)throw Error('Presentation cap no longer effective');}
}catch(e){report.failure=String(e);console.error(e);process.exitCode=1}finally{fs.writeFileSync(process.env.MUSIC_OUTPUT || '/tmp/nowherelands-music-checks.json',JSON.stringify(report,null,2));await browser.close()}})();
